//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorDetay
    {
        public int DoktorDetayID { get; set; }
        public int DoktorID { get; set; }
        public string Detay { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
    }
}
