//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS_Projesi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Doktorlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktorlar()
        {
            this.DoktorDetay = new HashSet<DoktorDetay>();
            this.Kriterler = new HashSet<Kriterler>();
            this.Randevular = new HashSet<Randevular>();
        }
    
        public int DoktorID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Poliklinik { get; set; }
        public string Unvan { get; set; }
        public System.DateTime Gun { get; set; }
        public System.TimeSpan Saat { get; set; }
        public bool RandevuDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoktorDetay> DoktorDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kriterler> Kriterler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevular> Randevular { get; set; }

        [NotMapped]
        public double Skor { get; set; }
    }
}
