//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kriterler
    {
        public int KriterID { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public Nullable<int> Deneyim { get; set; }
        public Nullable<int> Memnuniyet { get; set; }
        public Nullable<int> Iletisim { get; set; }
        public Nullable<int> TedaviMaliyetleri { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
    }
}
