//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int RandevuID { get; set; }
        public int DoktorID { get; set; }
        public int HastaID { get; set; }
        public System.DateTime Gun { get; set; }
        public System.TimeSpan Saat { get; set; }
        public string Poliklinik { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual Hastalar Hastalar { get; set; }
    }
}
